name: Release
on:
  workflow_dispatch:
env:
  NODE_VERSION: 14
defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure Git
        run: |
          git config user.name "Moritz Wiesinger"
          git config user.email "moritz.wiesinger@dynatrace.com"

      - name: Prepare GitHub Release Notes
        run: |
          npx standard-version -i RELEASE-BODY.md --skip.commit --skip.tag --skip.bump --header ""

      - name: Create release package
        id: create-release-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx standard-version
          echo ::set-output name=tag-name::$(git describe --tags --abbrev=0)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          release_name: ${{ steps.create-release-package.tag-name }}
          tag_name: ${{ steps.create-release-package.tag-name }}
          body_path: RELEASE-BODY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
