name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  NODE_VERSION: 14
defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up semantic-release
        run: npm install conventional-changelog-conventionalcommits @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github @semantic-release/changelog @semantic-release/git

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.ADVANCED_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "Moritz Wiesinger"
          GIT_AUTHOR_EMAIL: moritz.wiesinger@dynatrace.com
          GIT_COMMITTER_NAME: "Moritz Wiesinger"
          GIT_COMMITTER_EMAIL: moritz.wiesinger@dynatrace.com
        run: npx semantic-release
