name: Release
on:
  workflow_dispatch:
env:
  NODE_VERSION: 14
  RELEASE_NOTES_FILE: RELEASE-BODY.md
defaults:
  run:
    shell: bash
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure Git
        run: |
          git config user.name "Moritz Wiesinger"
          git config user.email "moritz.wiesinger@dynatrace.com"

      - name: Prepare GitHub Release Notes
        run: |
          npx standard-version@^9.3.1 -i "${{ env.RELEASE_NOTES_FILE }}" --skip.commit --skip.tag --header ""

      - name: Create release package
        id: create-release-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🚀 Creating release package now..."
          npx standard-version@^9.3.1

          echo "::set-output name=tag-name::$(git describe --tags --abbrev=0)"
          echo "⚡️ Pushing changes to remote repository..."
          git push --follow-tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.create-release-package.outputs.tag-name }}" --notes-file "${{ env.RELEASE_NOTES_FILE }}"
